# FLARE Setting
name : paper_examples
version:  1000_large_batch
description: Example to show how the large batch system works with multi-production and its timings

# b2luigi settings
batch_system: slurm
slurm_settings: 
  mem: 5GB