# FLARE Settings
name : paper_examples
version:  large_batch_example/run3
description: Paper examples of MC production, analysis workflow and full blown production. Will include this in paper as example
studydir: analysis/studies/large_mc_batch_example

# b2luigi settings
batch_system: slurm